[package]
name = "blub"
version = "0.1.0"
authors = ["Andreas Reich <r_andreas2@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.4"
winit = "0.22"
shaderc = "0.6"
notify = "5.0.0-pre.2"
cgmath = { git = "https://github.com/rustgd/cgmath", rev="50a345b", features=["rand"] }
enumflags2 = "^0.6"
rand = { version="0.7.3", features=["small_rng"] }
regex = "1"
lazy_static = "1.4"
more-asserts = "0.2"